# rustfmt.toml

# Maximum line width
max_width = 100

# Use 4 spaces for indentation
tab_spaces = 4

# Use spaces instead of tabs
use_tabs = false

# Whether to add a trailing comma in lists and tuples
trailing_comma = "Always"

# Whether to format code in specific situations
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
format_attributes = false
format_struct_lit = false
format_array_inits = false
format_match_arms = false
format_match_pattern = false
format_closure_brace = false
format_trait_impls = false
format_impls = false
format_type_alias = false
format_type_args = false
format_imports = false
reorder_imports = false
reorder_impl_items = false
reorder_trait_impl_items = false

# Whether to break lines exceeding the maximum width
wrap_comments = true
wrap_attributes = true
wrap_match_arms = true
wrap_return_type = true
wrap_struct_lit = true
wrap_impl_body = true
wrap_match_body = true
wrap_match_arm = true
wrap_chained_method_calls = true
wrap_macros = true

# Where to place items when breaking lines
use_try_shorthand = true
merge_imports = true
overflow_delimited_expr = false
overflow_binary_expr = false

# Where to put spaces in certain situations
space_before_colon = true
space_after_colon = true
space_after_comma = true
space_before_arrow = true
space_after_arrow = true
space_between_braces = true
