name: Test_Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update local toolchain
      run: |
        rustup update
        rustup component add clippy
    - name: Toolchain info
      run: |
        cargo --version --verbose
        rustc --version
        cargo clippy --version

    - name: Testlx 
      run: |
        cargo install sqlx-cli
        sqlx database setup -D ./test_db.sqlite
        cargo check
        cargo test --all --verbose
    
    - name: Build
      run: cargo build --release --verbose
